# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 903)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.gridLayout.addWidget(self.webEngineView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.mapGraph = QtWidgets.QMenu(self.menuData)
        self.mapGraph.setObjectName("mapGraph")
        self.sortedChart = QtWidgets.QMenu(self.menuData)
        self.sortedChart.setObjectName("sortedChart")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_Data_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_Data_2.setObjectName("actionExport_Data_2")
        self.actionBubble_Graph_Deaths_vs_Recovered = QtWidgets.QAction(MainWindow)
        self.actionBubble_Graph_Deaths_vs_Recovered.setObjectName("actionBubble_Graph_Deaths_vs_Recovered")
        self.actionMap_Graph = QtWidgets.QAction(MainWindow)
        self.actionMap_Graph.setObjectName("actionMap_Graph")
        self.actionSorted_Chart = QtWidgets.QAction(MainWindow)
        self.actionSorted_Chart.setObjectName("actionSorted_Chart")
        self.chartbycases = QtWidgets.QAction(MainWindow)
        self.chartbycases.setObjectName("chartbycases")
        self.chartbydeaths = QtWidgets.QAction(MainWindow)
        self.chartbydeaths.setObjectName("chartbydeaths")
        self.mapgraphbycases = QtWidgets.QAction(MainWindow)
        self.mapgraphbycases.setObjectName("mapgraphbycases")
        self.mapgraphbydeaths = QtWidgets.QAction(MainWindow)
        self.mapgraphbydeaths.setObjectName("mapgraphbydeaths")
        self.exportFigureSelection = QtWidgets.QAction(MainWindow)
        self.exportFigureSelection.setObjectName("exportFigureSelection")
        self.sortedChartByBoth = QtWidgets.QAction(MainWindow)
        self.sortedChartByBoth.setObjectName("sortedChartByBoth")
        self.bubbleGraphDaily = QtWidgets.QAction(MainWindow)
        self.bubbleGraphDaily.setObjectName("bubbleGraphDaily")
        self.bubbleGraphCumulative = QtWidgets.QAction(MainWindow)
        self.bubbleGraphCumulative.setObjectName("bubbleGraphCumulative")
        self.mapGraph.addAction(self.mapgraphbycases)
        self.mapGraph.addAction(self.mapgraphbydeaths)
        self.sortedChart.addAction(self.chartbycases)
        self.sortedChart.addAction(self.chartbydeaths)
        self.menuData.addAction(self.mapGraph.menuAction())
        self.menuData.addAction(self.sortedChart.menuAction())
        self.menuFile.addAction(self.exportFigureSelection)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuData.setTitle(_translate("MainWindow", "Tracker"))
        self.mapGraph.setTitle(_translate("MainWindow", "Map Graph"))
        self.sortedChart.setTitle(_translate("MainWindow", "Sorted Chart"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExport_Data_2.setText(_translate("MainWindow", "Export Data"))
        self.actionBubble_Graph_Deaths_vs_Recovered.setText(_translate("MainWindow", "Bubble Graph: Deaths vs Recovered"))
        self.actionMap_Graph.setText(_translate("MainWindow", "Map Graph"))
        self.actionSorted_Chart.setText(_translate("MainWindow", "Sorted Chart"))
        self.chartbycases.setText(_translate("MainWindow", "Sorted Chart By Cases"))
        self.chartbydeaths.setText(_translate("MainWindow", "Sorted Chart By Deaths"))
        self.mapgraphbycases.setText(_translate("MainWindow", "Map Graph By Cases"))
        self.mapgraphbydeaths.setText(_translate("MainWindow", "Map Graph By Deaths"))
        self.exportFigureSelection.setText(_translate("MainWindow", "Export Figure"))
        self.sortedChartByBoth.setText(_translate("MainWindow", "Sorted Chart By Both"))
        self.bubbleGraphDaily.setText(_translate("MainWindow", "Daily Recoveries vs Deaths"))
        self.bubbleGraphCumulative.setText(_translate("MainWindow", "Cumulative Recoveries vs Deaths"))
from PyQt5 import QtWebEngineWidgets
